cashflow/urls.py
from django.urls import path
from . import views

app_name = 'cashflow'

urlpatterns = [
    path('', views.CashflowListView.as_view(), name="flow-list"),
    path('flow-create/', views.CashFlowCreateView.as_view(), name="flow-create"),
    path('flow-update/<int:pk>/', views.CashFlowUpdateView.as_view(), name="flow-update"),
    path('flow-delete/<int:pk>/', views.CashFlowDeleteView.as_view(), name="flow-delete"),

    path('refrences/', views.refrence_data, name="refrence-list"),

    path('refrence-create/typeflow/', views.RefrenceTypeflowCreateView.as_view(), name="refrence-typeflow-create"),
    path('refrence-update/typeflow/<int:pk>/', views.RefrenceTypeflowUpdateView.as_view(), name="refrence-typeflow-update"),
    path('refrence-delete/typeflow/<int:pk>/', views.RefrenceTypeflowDeleteView.as_view(), name="refrence-typeflow-delete"),

    path('refrence-create/category/', views.RefrenceCategoryCreateView.as_view(), name="refrence-category-create"),
    path('refrence-update/category/<int:pk>/', views.RefrenceCategoryUpdateView.as_view(), name="refrence-category-update"),
    path('refrence-delete/category/<int:pk>/', views.RefrenceCategoryDeleteView.as_view(), name="refrence-category-delete"),

    path('refrence-create/subcategory/', views.RefrenceSubcategoryCreateView.as_view(), name="refrence-subcategory-create"),
    path('refrence-update/subcategory/<int:pk>/', views.RefrenceSubcategoryUpdateView.as_view(), name="refrence-subcategory-update"),
    path('refrence-delete/subcategory/<int:pk>/', views.RefrenceSubcategoryDeleteView.as_view(), name="refrence-subcategory-delete"),

    path('refrence-create/statusflow/', views.RefrenceStatusflowCreateView.as_view(), name="refrence-statusflow-create"),
    path('refrence-update/statusflow/<int:pk>/', views.RefrenceStatusflowUpdateView.as_view(), name="refrence-statusflow-update"),
    path('refrence-delete/statusflow/<int:pk>/', views.RefrenceStatusflowDeleteView.as_view(), name="refrence-statusflow-delete"),

    path('api/get-structure-data/', views.api_get_structure_data, name="api-get-structure-data")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cashflow.urls')),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name="main_page"),
]

cashflow/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название")
    typeflow = models.ForeignKey('TypeFlow', on_delete=models.PROTECT, related_name='categories', verbose_name="Тип движения")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название")
    supercategory = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='subcategories', verbose_name="Надкатегория")

    class Meta:
        verbose_name = "Подкатегория"
        verbose_name_plural = "Подкатегории"

    def __str__(self):
        return self.name


class StatusFlow(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название")

    class Meta:
        verbose_name = "Статус"
        verbose_name_plural = "Статусы"

    def __str__(self):
        return self.name


class TypeFlow(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название")

    class Meta:
        verbose_name = "Тип"
        verbose_name_plural = "Типы"

    def __str__(self):
        return self.name


class CashFlow(models.Model):
    amount = models.DecimalField(max_digits=30, decimal_places=2, verbose_name="Сумма")
    comment = models.TextField(null=True, blank=True, verbose_name="Комментарий")
    created_at = models.DateField(editable=True, verbose_name="Дата движения")
    typeflow = models.ForeignKey('TypeFlow', on_delete=models.PROTECT, related_name="cashflows", verbose_name="Тип движения")
    category = models.ForeignKey('Category', on_delete=models.PROTECT, related_name="cashflows", verbose_name="Категория")
    subcategory = models.ForeignKey('Subcategory', on_delete=models.PROTECT, related_name="cashflows", verbose_name="Подкатегория")
    status = models.ForeignKey('StatusFlow', on_delete=models.PROTECT, related_name="cashflows", verbose_name="Статус")
    
    class Meta:
        verbose_name = "Движение средств"
        verbose_name_plural = "Движения средств"
        ordering = ["-created_at", "-amount"]

    def __str__(self):
        return str(self.amount)

    def clean(self):
        super().clean()
        if self.category.typeflow != self.typeflow:
            raise ValidationError({'category': f"Категория {self.category.name} не принадлежит типу {self.typeflow.name}"})
        if self.subcategory.supercategory != self.category:
            raise ValidationError({'subcategory': f"Подкатегория {self.subcategory.name} не принадлежит категории {self.category.name}"})

    def save(self, *args, **kwargs):
        # для автозаполнения времени создания + сохранения возможности редактирования
        if not self.pk:
            if not self.created_at:
                self.created_at = timezone.now()

        # для запуска валидации в любом случае
        self.full_clean()
        super().save(*args, **kwargs)

cashflow/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.http import HttpRequest, JsonResponse
from django.db.models import Q
from django.http import JsonResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models.deletion import ProtectedError

from .models import CashFlow, Category, StatusFlow, Subcategory, TypeFlow, StatusFlow
from .forms import CategoryCreateUpdateForm, CreateUpdateCashFlowForm, FilterCashFlowForm, StatusflowCreateUpdateForm, SubcategoryCreateUpdateForm, TypeflowCreateUpdateForm


def api_get_structure_data(request):
    """
    ajax-запрос структуры типов, категорий, подкатегорий, статусов
    """
    typeflows = dict(TypeFlow.objects.values_list('pk', "name"))
    categories = dict(Category.objects.values_list('pk', "name"))
    subcategories = dict(Subcategory.objects.values_list('pk', "name"))
    statuses = dict(StatusFlow.objects.values_list('pk', "name"))

    typeflows_and_categories = {}
    for typeflow in TypeFlow.objects.all():
        typeflows_and_categories[typeflow.pk] = [category.pk for category in typeflow.categories.all()]

    categories_and_subcategories = {} 
    for category in Category.objects.all():
        categories_and_subcategories[category.pk] = [subcategory.pk for subcategory in category.subcategories.all()]

    filter_data = {}
    filter_data['typeflows'] = typeflows
    filter_data['categories'] = categories
    filter_data['subcategories'] = subcategories
    filter_data['statuses'] = statuses

    filter_data['typeflows_and_categories'] = typeflows_and_categories
    filter_data['categories_and_subcategories'] = categories_and_subcategories

    filter_data = JsonResponse(filter_data, encoder=DjangoJSONEncoder, safe=False)
    
    return filter_data



class CashflowListView(ListView):
    """
    Список движений.
    """
    model = CashFlow
    template_name = "cashflow/flow_list.html"

    def get_queryset(self):
        filters = Q()
        if start_date := self.request.GET.get('start_date'):
            filters &= Q(created_at__gte=start_date)
        if end_date := self.request.GET.get('end_date'):
            filters &= Q(created_at__lte=end_date)
        if typeflow := self.request.GET.get('typeflow'):
            filters &= Q(typeflow=typeflow)
        if category := self.request.GET.get('category'):
            filters &= Q(category=category)
        if subcategory := self.request.GET.get('subcategory'):
            filters &= Q(subcategory=subcategory)
        if status := self.request.GET.get('status'):
            filters &= Q(status=status)

        return CashFlow.objects.filter(filters)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter_form"] = FilterCashFlowForm
        return context


class CashFlowCreateView(CreateView):
    model = CashFlow
    form_class = CreateUpdateCashFlowForm
    template_name = 'cashflow/flow_create.html'
    success_url = reverse_lazy('cashflow:flow-list')
    context_object_name = 'flow'


class CashFlowUpdateView(UpdateView):
    model = CashFlow
    form_class = CreateUpdateCashFlowForm
    template_name = 'cashflow/flow_update.html'
    success_url = reverse_lazy('cashflow:flow-list')
    context_object_name = 'flow'


class CashFlowDeleteView(DeleteView):
    model = CashFlow
    template_name = 'cashflow/flow_confirm_delete.html'
    success_url = reverse_lazy('cashflow:flow-list')
    context_object_name = 'flow'


def refrence_data(request):
    """
    Страничка всех справочников.
    """
    typeflows = TypeFlow.objects.all()
    categories = Category.objects.all()
    subcategories = Subcategory.objects.all()
    statuses = StatusFlow.objects.all()
    context = {"typeflows": typeflows,
               "categories": categories,
               "subcategories": subcategories,
               "statuses": statuses,
               }
    return render(request, 'cashflow/refrence_list.html', context)


####################   создание записей справочников     ######################
class RefrenceTypeflowCreateView(CreateView):
    model = TypeFlow
    form_class = TypeflowCreateUpdateForm
    template_name = 'cashflow/refrence_typeflow_create.html'
    success_url = reverse_lazy("cashflow:refrence-list")
    context_object_name = 'typeflow'


class RefrenceCategoryCreateView(CreateView):
    model = Category
    form_class = CategoryCreateUpdateForm
    template_name = 'cashflow/refrence_category_create.html'
    success_url = reverse_lazy("cashflow:refrence-list")
    context_object_name = 'category'


class RefrenceSubcategoryCreateView(CreateView):
    model = Subcategory
    form_class = SubcategoryCreateUpdateForm
    template_name = 'cashflow/refrence_subcategory_create.html'
    success_url = reverse_lazy("cashflow:refrence-list")
    context_object_name = 'subcategory'


class RefrenceStatusflowCreateView(CreateView):
    model = StatusFlow
    form_class = StatusflowCreateUpdateForm
    template_name = 'cashflow/refrence_statusflow_create.html'
    success_url = reverse_lazy("cashflow:refrence-list")
    context_object_name = 'statusflow'


####################   удаление записей справочников     ######################
class RefrenceTypeflowDeleteView(DeleteView):
    model = TypeFlow
    template_name = 'cashflow/refrence_typeflow_confirm_delete.html'
    success_url = reverse_lazy('cashflow:refrence-list')
    context_object_name = 'typeflow'

    # не хочу определять целый __init__ для только одной вспомогательной перменной
    related_objects = None

    def get(self, request, *args, **kwargs):
        """
        Нужно проинформировать об списке связанных записей до нажатия кнопки подтверждения удаления.
        """
        typeflow = self.get_object()
        if related_objects := typeflow.categories.all():
            self.related_objects = related_objects
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Для информирования об наличии связанных записей
        """
        context = super().get_context_data(**kwargs)
        if self.related_objects:
            context['related_objects'] = self.related_objects
        return context


class RefrenceCategoryDeleteView(DeleteView):
    model = Category
    template_name = 'cashflow/refrence_category_confirm_delete.html'
    success_url = reverse_lazy('cashflow:refrence-list')
    context_object_name = 'category'

    related_objects = None


    def get(self, request, *args, **kwargs):
        """
        Нужно проинформировать об списке связанных записей до нажатия кнопки подтверждения удаления.
        """
        category = self.get_object()
        if related_objects := category.subcategories.all():
            self.related_objects = related_objects
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Для информирования об наличии связанных записей
        """
        context = super().get_context_data(**kwargs)
        if self.related_objects:
            context['related_objects'] = self.related_objects
        return context


class RefrenceSubcategoryDeleteView(DeleteView):
    model = Subcategory
    template_name = 'cashflow/refrence_subcategory_confirm_delete.html'
    success_url = reverse_lazy('cashflow:refrence-list')
    context_object_name = 'subcategory'
    
    related_objects = None

    def get(self, request, *args, **kwargs):
        """
        Нужно проинформировать об списке связанных записей до нажатия кнопки подтверждения удаления.
        """
        subcategory = self.get_object()
        if related_objects := subcategory.cashflows.all():
            self.related_objects = related_objects
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Для информирования об наличии связанных записей
        """
        context = super().get_context_data(**kwargs)
        if self.related_objects:
            context['related_objects'] = self.related_objects
        return context


class RefrenceStatusflowDeleteView(DeleteView):
    model = StatusFlow
    template_name = 'cashflow/refrence_statusflow_confirm_delete.html'
    success_url = reverse_lazy('cashflow:refrence-list')
    context_object_name = 'statusflow'

    related_objects = None

    def get(self, request, *args, **kwargs):
        """
        Нужно проинформировать об списке связанных записей до нажатия кнопки подтверждения удаления.
        """
        statusflow = self.get_object()
        if related_objects := statusflow.cashflows.all():
            self.related_objects = related_objects
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Для информирования об наличии связанных записей
        """
        context = super().get_context_data(**kwargs)
        if self.related_objects:
            context['related_objects'] = self.related_objects
        return context


##################   редактирование записей справочников    ###################
class RefrenceTypeflowUpdateView(UpdateView):
    model = TypeFlow
    form_class = TypeflowCreateUpdateForm
    template_name = 'cashflow/refrence_typeflow_update.html'
    success_url = reverse_lazy('cashflow:refrence-list')
    context_object_name = 'typeflow'


class RefrenceCategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryCreateUpdateForm
    template_name = 'cashflow/refrence_category_update.html'
    success_url = reverse_lazy('cashflow:refrence-list')
    context_object_name = 'category'


class RefrenceSubcategoryUpdateView(UpdateView):
    model = Subcategory
    form_class = SubcategoryCreateUpdateForm
    template_name = 'cashflow/refrence_subcategory_update.html'

templates/cashflow/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>{% block title %}{% endblock title %}</title>

</head>

<body>
    {% include 'cashflow/_header.html' %}

    <div class="container mt-4">
        <!-- Блок для заголовка страницы -->
        <h1 class="mb-4">{% block page_title %}{% endblock page_title %}</h1>
        
        <div class="content">
            {% block content %}
            {% endblock content %}
        </div>

    </div>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/cashflow/_header.html
<header class="bg-dark text-white mb-4">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="{% url 'cashflow:flow-list' %}">Список движений</a>
            
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cashflow:flow-create' %}">Создать движение</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cashflow:refrence-list' %}">Справочники</a>
                    </li>
                </ul>
                
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'admin:index' %}">Админ-панель</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'admin:login' %}">Вход</a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
</header>

templates/cashflow/createflow.html
{% extends 'cashflow/_base.html' %}

{% block title %}Создать движение{% endblock %}

{% block page_title %}Создать новое движение{% endblock %}
{% block content %}
    <br>
    <form id="form-create-flow" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ success_url }}" class="btn btn-secondary">Отменить все</a>
    </form>
{% endblock %}

templates/cashflow/flow_confirm_delete.html
{% extends 'cashflow/_base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Удалить запись на {{ flow.amount }}₽ ({{ flow.category.name }})?</p>
  <button type="submit" class="btn btn-danger">Удалить</button>
  <a href="{{ view.success_url }}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock content %}

templates/cashflow/flow_list.html
{% extends 'cashflow/_base.html' %}

{% block title %}Главная{% endblock %}

{% block page_title %}Движения денежных средств{% endblock %}

{% block content %}
    <h3>Фильтр движений</h3>

    <form id="form-filter-list-flow" method="GET" class="form-inline">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>{{ filter_form.start_date.label_tag }}</th>
                        <th>{{ filter_form.end_date.label_tag }}</th>
                        <th>{{ filter_form.typeflow.label_tag }}</th>
                        <th>{{ filter_form.category.label_tag }}</th>
                        <th>{{ filter_form.subcategory.label_tag }}</th>
                        <th>{{ filter_form.status.label_tag }}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ filter_form.start_date }}</td>
                        <td>{{ filter_form.end_date }}</td>
                        <td>{{ filter_form.typeflow }}</td>
                        <td>{{ filter_form.category }}</td>
                        <td>{{ filter_form.subcategory }}</td>
                        <td>{{ filter_form.status }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <button type="submit" class="btn btn-primary">Фильтровать</button>
        <a href="{% url 'cashflow:flow-list' %}" class="btn btn-secondary ml-2">Отменить все фильтры</a>
    </form>

    <br>
    <hr>

    <h3>Список транзакций</h3>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>Дата</th>
                    <th>Сумма</th>
                    <th>Тип</th>
                    <th>Категория</th>
                    <th>Подкатегория</th>
                    <th>Статус</th>
                    <th>Комментарий</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for flow in object_list %}
                    <tr>
                        <td><a href="{% url 'cashflow:flow-update' flow.pk %}" class="btn btn-sm btn-link text-primary" title="Редактировать">✎ </a></td>
                        <td>{{ flow.created_at|date:"d.m.Y" }}</td>
                        <td>{{ flow.amount }} ₽</td>
                        <td>{{ flow.typeflow.name }}</td>
                        <td>{{ flow.category.name }}</td>
                        <td>{{ flow.subcategory.name }}</td>
                        <td>{{ flow.status.name }}</td>
                        <td>{{ flow.comment }}</td>

                        <td><a href="{% url 'cashflow:flow-delete' flow.pk %}" class="btn btn-sm btn-link text-primary" title="Удалить">🗑</a></td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="text-center">Нет данных</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>



{% endblock %}

templates/cashflow/flow_update.html
{% extends 'cashflow/_base.html' %}

{% block content %}
<form id="form-update-flow" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ success_url }}" class="btn btn-secondary">Вернуть изменения</a>
</form>
{% endblock %}

templates/cashflow/refrence_category_confirm_delete.html
{% extends 'cashflow/_base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% if related_objects %}
        <p>Невозможно удалить категорию {{ category.name }}. Имеются связанные подкатегории:</p>
        {% for subcategory in related_objects %}
            <p>{{ subcategory.name }}</p>
        {% endfor %}
    {% else %}
        <p>Удалить категорию {{ category.name }}?</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
    {% endif %}
    <a href="{{ view.success_url }}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock content %}

templates/cashflow/refrence_category_create.html
{% extends 'cashflow/_base.html' %}

{% block title %}Создать категорию{% endblock %}

{% block page_title %}Создать новую категорию{% endblock %}
{% block content %}
    <br>
    <form id="form-create-refrence-category" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ success_url }}" class="btn btn-secondary">Отменить все</a>
    </form>
{% endblock %}

templates/cashflow/refrence_category_update.html
{% extends 'cashflow/_base.html' %}

{% block title %}Редактировать категорию{% endblock %}

{% block page_title %}Редактировать категорию{% endblock %}
{% block content %}
    <br>
    <form id="form-update-refrence-category" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ view.success_url }}" class="btn btn-secondary">Отменить все</a>
    </form>
{% endblock %}

templates/cashflow/refrence_statusflow_update.html
{% extends 'cashflow/_base.html' %}

{% block title %}Редактировать статус{% endblock %}

{% block page_title %}Редактировать статус{% endblock %}
{% block content %}
    <br>
    <form id="form-update-refrence-statusflow" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ view.success_url }}" class="btn btn-secondary">Отменить все</a>
    </form>
{% endblock %}

templates/cashflow/refrence_subcategory_confirm_delete.html
{% extends 'cashflow/_base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% if related_objects %}
        <p>Невозможно удалить подкатегорию {{ subcategory.name }}. Имеются связанные записи движения денежных средства:</p>
        {% for cashflow in related_objects %}
            <p>{{ cashflow.amount }} ₽, {{ cashflow.created_at }}</p>
        {% endfor %}
    {% else %}
        <p>Удалить подкатегорию {{ subcategory.name }}?</p>
        <button type="submit" class="btn btn-danger">Удалить</button>
    {% endif %}
    <a href="{{ view.success_url }}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock content %}

templates/cashflow/refrence_subcategory_create.html
{% extends 'cashflow/_base.html' %}

{% block title %}Создать подкатегорию{% endblock %}

{% block page_title %}Создать новую подкатегорию{% endblock %}
{% block content %}
    <br>
    <form id="form-create-refrence-subcategory" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ success_url }}" class="btn btn-secondary">Отменить все</a>
    </form>
{% endblock %}

templates/cashflow/refrence_subcategory_update.html
{% extends 'cashflow/_base.html' %}

{% block title %}Редактировать подкатегорию{% endblock %}

{% block page_title %}Редактировать подкатегорию{% endblock %}
{% block content %}
    <br>
    <form id="form-update-refrence-subcategory" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ view.success_url }}" class="btn btn-secondary">Отменить все</a>
    </form>
{% endblock %}

templates/cashflow/refrence_typeflow_update.html
{% extends 'cashflow/_base.html' %}

{% block title %}Редактировать тип{% endblock %}

{% block page_title %}Редактировать тип движения{% endblock %}
{% block content %}
    <br>
    <form id="form-update-refrence-typeflow" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ view.success_url }}" class="btn btn-secondary">Отменить все</a>
    </form>
{% endblock %}